Renamed several files Updated readme install instructions Moved gdf to be it's own function instead of an alias

diff --git a/git-shortcuts b/git-shortcuts
--- a/git-shortcuts
+++ b/git-shortcuts
@@ -20,7 +20,6 @@ alias gch='f(){ git checkout hotfix/$1 2>/dev/null; git branch -u origin/hotfix/
 alias gcr='f(){ git checkout release/$1 2>/dev/null; git branch -u origin/release/$1 release/$1 >/dev/null; }; f'
 alias gcs='f(){ git checkout support/$1 2>/dev/null; git branch -u origin/support/$1 support/$1 >/dev/null; }; f'
 alias gd='git diff'
-alias gdf='f(){ if [[ -z "$1" ]]; then printf "Git Diff a File (or Directory) between x commits ago and y commits ago \nError: No inputs given.\n\nSyntax: gdf FILE [commits ago] [commits ago]\n\nExample to see changes of a file between last commit and two commits ago:\ngdf FILE 1 0\n"; return; fi; git diff HEAD~$2 HEAD~$3 "$1"; }; f'
 alias gf='git fetch'
 alias ghash='git branch --contains'
 alias gitcred='git config --global credential.helper "store --file ~/.git-credentials"'
@@ -48,6 +47,52 @@ alias renamebranch='git branch -m'
 alias stash='git stash'
 alias restore='git stash pop'
 alias wip='git commit -am "WIP"'
+
+
+# Git Diff a File/Dir
+gdf() {
+  if [[ -z "$1" ]]; then
+    printf "\n\e[36mGit Diff a File (or Directory) between X commits ago and Y commits ago\e[0m\n\n"
+    printf "\e[31mError: No inputs given.\e[0m\n\n"
+    printf "\e[1;34mSyntax: gdf FILE [X commits ago] [Y commits ago]\e[0m\n\n"
+    printf "Example: to see changes of a file between previous revision and current committed revision:\ngdf FILE 1 0\n\n"
+    printf "Example: to see changes of a file between four commits ago and previous revision:\ngdf FILE 3 1\n\n"
+    printf "Example: to use a wildcard, put it in single quotes:\ngdf 'customer*' 1 0\n\n"
+    printf "Note: If X and Y values are ommitted, it will default to diff of previous version and current version.\n"
+    printf "Note: It is recommended to be consistent between older commits for the X value and newer commits for\n"
+    printf "      the Y value. Otherwise, it will appear as if the code written was deleted.\n\n"
+    return
+  fi
+  local start end
+  test -z "$2" && start=1 || start="$2"
+  test -z "$3" && end=1 || end="$3"
+  git diff HEAD~$2 HEAD~$3 "$1"
+}
+
+
+# Set up or Fix a git flow directory
+gitflow() {
+    local git_flow_config="master\ndevelop\nfeature/\nbugfix/\nrelease/\nhotfix/\nsupport/\n\n\n"
+    # Check to see if git flow is initialized and is correctly configured
+    echo "Checking git flow config..."
+    local git_flow_check=$(git flow config 2>/dev/null)
+    if [[ $? -eq 1 ]]; then
+      # Check if Git Flow is installed
+      local git_check=$(git flow 2>&1 | grep 'not a git command' | wc -l)
+      if [[ $git_check -eq 1 ]]; then
+        printf "\nError: Git Flow is not installed.\n\nPlease run: \"apt install git-flow\"\n\n"
+        return 1
+      fi
+      # Set Git Flow config
+      echo "Configuring git flow"
+      printf "$git_flow_config" | git flow init >/dev/null
+    elif [[ $(echo "$git_flow_check" | grep "Feature branch prefix: feature/" | wc -l) -eq 0 ]]; then
+      # Force reset of Git Flow config
+      echo "Reconfiguring git flow"
+      printf "$git_flow_config" | git flow init -f >/dev/null
+    fi
+}
+
 
 # Display Alias Menu
 display_git_aliases() {
